Boot web permissions project
ontimize/ontimize-examples pull request #1
Opened 2023-06-12 08:18 UTC by javierFernandezMendez

2023-06-20 16:15 UTC, daniel-grana requested changes

2023-06-20 16:15 UTC, daniel-grana commented on projectwiki-frontend/package.json
> +    "ontimize-web-ngx-filemanager": "8.5.6",
No se necesita para nada la dependencia del filemanager en esta demo no?

2023-06-21 11:36 UTC, daniel-grana approved these changes

2023-07-11 07:04 UTC, pmkirsten approved these changes
All ok

2023-07-20 10:24 UTC, patricia-martinez-imatia approved these changes

2023-07-20 21:07 UTC, daniel-grana approved these changes

2023-07-21 05:03 UTC, merged